site_name: Dino's documentation
site_url: https://willpinha.github.io/dino
repo_url: https://github.com/willpinha/dino
repo_name: willpinha/dino
plugins: 
  - typeset 
theme:
  name: material
  icon:
    logo: material/book-open 
  palette:
    scheme: slate 
    primary: green
    accent: lime 
  features:
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.top
    - navigation.sections
    - navigation.footer
nav:
  - index.md
  - The basics:
    - the-basics/handlers-routing.md
    - the-basics/error-handling.md
    - the-basics/middlewares.md
    - the-basics/requests.md
    - the-basics/responses.md
    - the-basics/logging.md
    - the-basics/testing.md
  - Cheat sheet:
    - cheat-sheet/net-http.md
  - Database:
    - database/getting-started.md
    - database/relational.md
    - database/document-based.md
  - Middlewares:
    - middlewares/recover.md
    - middlewares/access-log.md
  - Guides:
    - guides/monitoring-with-grafana.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  generator: false